config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls','users'), namespace='users')),
    path('', include(('urlshortner.urls','urlshortner'), namespace='urlshortner')),
]

urlshortner/urls.py
from django.urls import path
from .views import RedirectToLinkView, ShortenLinkView, MyLinksView
 
urlpatterns = [
    path('', ShortenLinkView.as_view(), 
        name="shortenlinkview"),
    path('my-links', MyLinksView.as_view(), 
        name="mylinksview"),
    path('<slug:url_slug>', RedirectToLinkView.as_view()),
]

users/urls.py
from django.urls import path
from .views import LogInView, SignUpView, LogOutView, SettingsView

urlpatterns = [
    path('login', LogInView.as_view(), name="loginview"),
    path('signup', SignUpView.as_view(), name="signupview"),
    path('logout', LogOutView.as_view(), name="logoutview"),
    path('settings/<pk>', SettingsView.as_view(), name="settingsview"),
]

urlshortner/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()

class Link(models.Model):
    owner = models.ForeignKey(User, null=True, blank=True, 
        on_delete=models.CASCADE)
    long_url = models.URLField(max_length=250)
    short_slug = models.SlugField(max_length=50, unique=True)
    nb_hits = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.long_url}, short is: {self.short_slug}"

users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

urlshortner/forms.py
from django import forms

class LinkForm(forms.Form):
    long_url = forms.URLField(label='URL to shorten', max_length=250)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from .models import CustomUser


class LoginForm(AuthenticationForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

class SignupForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

class EditForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

urlshortner/views.py
from django.contrib.auth import login
from django.forms.fields import NullBooleanField
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Link
from .forms import LinkForm
from .utils import generate_unique_slug

class RedirectToLinkView(View):

    def get(self, request, url_slug):

        # Get redirection link
        link_obj = get_object_or_404(Link, short_slug=url_slug)
        redirect_to = link_obj.long_url
        
        # Counting the number of redirects
        link_obj.nb_hits += 1
        link_obj.save()

        return HttpResponseRedirect(redirect_to)

class ShortenLinkView(View):

    def get(self, request):
        form = LinkForm()
        return render(request, "urlshortner/index.html", {'form': form})

    def post(self, request):

        def get_user():
            if request.user.is_anonymous:
                return None
            else:
                return request.user

        # create a form instance and populate it with data from the request:
        form = LinkForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            shortened_url = Link(
                owner=get_user(),
                long_url= form.cleaned_data['long_url'],
                short_slug= generate_unique_slug()
            )
            shortened_url.save()
            return render(
                request, "urlshortner/link-created.html",
                {
                    'shorten_link': shortened_url.short_slug,
                    'domain': request.build_absolute_uri('/')[:-1]
                }
            )

class MyLinksView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        my_links = Link.objects.filter(owner=user)

        return render(
            request, "urlshortner/my-links.html",
            {
                'my_links': my_links,
                'domain': request.build_absolute_uri('/')[:-1]
            }
        )

users/views.py
from django.views import View
from django.views.generic.edit import UpdateView
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth import get_user_model

from .forms import LoginForm, SignupForm
from .models import CustomUser

class LogInView(View):

    def get(self, request):
        form = LoginForm()
        return render(request, "users/login.html", {'form': form})

    def post(self, request):
        # create a form instance and populate it with data from the request:
        form = LoginForm(data=request.POST)
        # check whether it's valid:
        if form.is_valid():
            user = authenticate(email=form.cleaned_data['username'], 
                        password=form.cleaned_data['password'])
            
            if user is not None:
                login(request, user)
                return redirect('/', user=user)
            else:
                #error cant login
                messages.add_message(request, messages.ERROR, 'Cannot login with the provided credentials.')
        messages.add_message(request, messages.ERROR, 'Form data is invalid.')
        return render(request, "users/login.html", {'form': form})



class SignUpView(View):

    def get(self, request):
        form = SignupForm()
        return render(request, "users/signup.html", {'form': form})

    def post(self, request):
        # create a form instance and populate it with data from the request:
        form = SignupForm(data=request.POST)
        # check whether it's valid:
        if form.is_valid():
            print(form.cleaned_data)
            user = get_user_model().objects.create_user(
                    email=form.cleaned_data['email'], 
                    password=form.cleaned_data['password1'])
           
            if user is not None:
                login(request, user)
                return redirect('/', user=user)

        messages.add_message(request, messages.ERROR, 'Form data is invalid.')
        return render(request, "users/signup.html", {'form': form})

class LogOutView(View):

    def get(self, request):
        logout(request)
        return render(request, 'users/loggedout.html')


class SettingsView(UpdateView):
    model = CustomUser
    fields = ['email', 'first_name', 'last_name']
    template_name = 'users/settings.html'

    def get_success_url(self):
        user_id = self.request.user.id
        redirect_to = f'/settings/{user_id}'
        messages.add_message(self.request, messages.SUCCESS, 'Profile updated successfully.')
        return redirect_to

urlshortner/templates/urlshortner/header.html
<html>
  {% load static %}
  <head>
    <link rel="stylesheet" href="{% static 'urlshortner/css/style.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap"
      rel="stylesheet"
    />
  </head>
  {% if not user.is_anonymous %}
  <header>
    <ul>
      <li><a href="{% url 'urlshortner:shortenlinkview' %}">Home</a></li>
      <li><a href="{% url 'urlshortner:mylinksview' %}">My links</a></li>
      <li>
        <a href="{% url 'users:settingsview' user.id %}">Settings</a>
      </li>
      <li class="last">
        {% if not user.is_anonymous %}
        <span>Logged in as {{ user }}</span> 
        {%endif %}
        <a href="{% url 'users:logoutview' %}">Log out</a>
      </li>
    </ul>
  </header>
  {% else %}
  <header>
    <ul>
      <li><a href="{% url 'urlshortner:shortenlinkview' %}">Home</a></li>
      <li><a href="{% url 'users:signupview' %}">Sign up</a></li>
      <li><a href="{% url 'users:loginview' %}">Log in</a></li>
    </ul>
  </header>
  {% endif %}
</html>

urlshortner/templates/urlshortner/index.html
  {% include "urlshortner/header.html" %}
  {% load static %} 
  
  <div class="imgSection">
    <img class="illu" src="{% static 'urlshortner/img/031.png' %}"/>
  </div>
  <div class="centralSection">
  <div id="centerBox">
    <h1>Fill up the form to shorten your URL</h1>
    <form action="{% url 'urlshortner:shortenlinkview' %}" method="post">
      {% csrf_token %} {{ form }}
      <input type="submit" value="🔗 Make it short" />
    </form>
  </div>
</div>
  

urlshortner/templates/urlshortner/link-created.html
{% include "urlshortner/header.html" %}
<div class="centralSection">
  <h1 class="colored">Here is your shorten link :</h1>
  <a href="{{ domain }}/{{ shorten_link }}">
    <span class="shortUrl">{{ domain }}/{{ shorten_link }}</span>
  </a>

  {%if user.is_anonymous%}
  <div>
    <br />
    <span class="shortUrl"
      >Sign up to access data on how many people click your shorten link:</span
    >
    <a href="{% url 'users:signupview' %}" class="shortUrl">Free sign up</a>
  </div>
  {% endif %}
</div>

urlshortner/templates/urlshortner/my-links.html
{% include "urlshortner/header.html" %}
<div class="centralSection">
  <h1 class="colored">
    Hey {{ user.first_name }}, find below a list of all the shortened URLs you
    created
  </h1>
  <br />
  {% if my_links|length == 0 %}
  <br />
  <h1 class="colored">You don't have any link created yet.</h1>
  {% else %}
  <table class="paleBlueRows">
    <thead>
      <tr>
        <th scope="col">Previous URL</th>
        <th scope="col">New URL</th>
        <th scope="col"># Nb. hits</th>
      </tr>
    </thead>
    {% for link in my_links %}
    <tr>
      <td>{{ link.long_url }}</td>
      <td>
        <a href="{{ domain }}/{{ link.short_slug }}">
          {{ domain }}/{{ link.short_slug }}
        </a>
      </td>
      <td>{{ link.nb_hits }}</td>
    </tr>
    {% endfor %}
  </table>
  {% endif %}
</div>

users/templates/users/loggedout.html
<html>
  {% include "urlshortner/header.html" %}
  <div class="centralSection">
    <h1 class="colored">You have been successfully logged out</h1>
    <a href="{% url 'urlshortner:shortenlinkview' %}" class="btn">
      Go back to the app
    </a>
  </div>
</html>

users/templates/users/login.html
<html>
  {% include "urlshortner/header.html" %} {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li>
      {% if message.tags %}
      <span class="{{ message.tags }}">{% endif %}{{ message }}</span>
    </li>
    {% endfor %}
  </ul>
  {% endif %}
  <div class="centralSection">
    <h1 class="colored">Fill up the form to log in</h1>
    <form action="{% url 'users:loginview' %}" method="post">
      {% csrf_token %} {{ form }}
      <input type="submit" value="Submit" />
    </form>
  </div>
</html>

users/templates/users/settings.html
<html>
  {% include "urlshortner/header.html" %} {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li>
      {% if message.tags %}
      <span class="{{ message.tags }}">{% endif %}{{ message }}</span>
    </li>
    {% endfor %}
  </ul>
  {% endif %}
  <div class="centralSection">
    <h1 class="colored">Settings & Profile</h1>
    <form method="post">
      {% csrf_token %} {{ form.as_p }}
      <input type="submit" value="Save" />
    </form>
  </div>
</html>

users/templates/users/signup.html
<html>
  {% include "urlshortner/header.html" %}
  <div class="centralSection">
    <h1 class="colored">Fill up the form to sign up</h1>
    <form action="{% url 'users:signupview' %}" method="post">
      {% csrf_token %} {{ form }}
      <input type="submit" value="Submit" />
    </form>
  </div>
</html>